apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: patch-pv-reclaim-policy
  namespace: dev
spec:
  rules:
  - name: reclaim-policy-on-pvc-deletion
    match:
      resources:
        kinds:
        - PersistentVolume
    validate:
      message: "PV's reclaim policy should be set to 'Retain' when the related PVC is deleted"
      pattern:
        spec:
          persistentVolumeReclaimPolicy: "!Retain"
    mutate:
      patches:
      - op: replace
        path: /spec/persistentVolumeReclaimPolicy
        value: Retain
        when:
          key: "pvcStatus"
          pattern: "Deleted"
          condition: Equals
          resourceSelector:
            name: "{request.object.spec.claimRef.name}"
            namespace: "{request.object.spec.claimRef.namespace}"
